spring.application.name=smarttask

spring.datasource.url=jdbc:mysql://localhost:3306/smarttask_db
spring.datasource.username=root
spring.datasource.password=Sha72.....

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

jwt.secret=smarttask_super_secret_key_for_jwt_2024_minimum_256_bits
jwt.expiration=86400000